// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const useEffect: typeof import('react')['useEffect']
  const useState: typeof import('react')['useState']
}
export {}
